// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/manga/GetChapterList": {
            "get": {
                "description": "получения ссылок на главы манги. На вход подается ссылка на мангу с секцией chaptets. Например, https%3A%2F%2Fmangalib.me%2Fo-ju-yesuyeo%3Fsection%3Dchapters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manga"
                ],
                "operationId": "manga-get-chapter-list",
                "parameters": [
                    {
                        "type": "string",
                        "name": "manga_url",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.GetChapterListResponse"
                        }
                    }
                }
            }
        },
        "/manga/GetChapterPages": {
            "get": {
                "description": "получения массива байт картинок с метаданными",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manga"
                ],
                "operationId": "manga-get-chapter-pages",
                "parameters": [
                    {
                        "type": "string",
                        "name": "chapter_url",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "person_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.GetChapterPagesResponse"
                        }
                    }
                }
            }
        },
        "/manga/SendToEbook": {
            "post": {
                "description": "различные взаимодействия с мангой",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manga"
                ],
                "operationId": "manga-controller",
                "parameters": [
                    {
                        "description": "chapter url and person info",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.SendToEbookRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.SendToEbookResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.GetChapterListResponse": {
            "type": "object",
            "properties": {
                "chapter_urls": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "manga_name": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "domain.GetChapterPagesResponse": {
            "type": "object",
            "properties": {
                "manga_name": {
                    "type": "string"
                },
                "pages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ImageBody"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "domain.ImageBody": {
            "type": "object",
            "properties": {
                "file_name": {
                    "type": "string"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "domain.PersonInfo": {
            "type": "object",
            "properties": {
                "person_id": {
                    "type": "string"
                },
                "telegram_id": {
                    "type": "integer"
                }
            }
        },
        "domain.SendToEbookRequest": {
            "type": "object",
            "properties": {
                "chapter_url": {
                    "type": "string"
                },
                "person": {
                    "$ref": "#/definitions/domain.PersonInfo"
                }
            }
        },
        "domain.SendToEbookResponse": {
            "type": "object",
            "properties": {
                "manga_name": {
                    "type": "string"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "@0.9",
	Host:             "matvey-inc",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Manga parser",
	Description:      "swagger для api к мангапарсеру",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
